version: '3.8'
services:
  kafka:
    container_name: kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb:
    container_name: filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - filterdb:/data/filterdb
  mongodbInvoice:
    container_name: invoicedb
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - invoicedb:/data/invoicedb
  inventorydb:
    container_name: inventorydb
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - inventorydb:/data/db/inventorydb
volumes:
  kafka_data:
  filterdb:
  invoicedb:
  inventorydb:
