spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/astavist/config-server-t2
  profiles:
    active: dev
server:
  port: 8888
