spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/keremerdogan1023/config-server-micro
  profiles:
    active: dev
server:
  port: 8888
